name: Accuracy checker Python3.8

on:
  pull_request:
    branches: '**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Pip install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-deps -r ci/requirements-ac-test.txt
          python -m pip install --no-deps tools/accuracy_checker
      - name: python -m pytest tools/accuracy_checker
        run: |
          python -m pytest tools/accuracy_checker
      - name: Pip install and run pylint
        working-directory: ./tools/accuracy_checker
        run: |
          python -m pip install pylint==2.10.2
          PYTHONPATH=. python -m pylint --rcfile=.pylintrc `find -wholename '?*/**/*.py' -not -path "./tests/*" -not -path "./build/*"`
